# =============================================
# SITE CONFIG
# =============================================

name: Tawja
homepage: http://www.tawja.org
lang: en
slogan: Methodology & Toolbox to build modular modern applications
year: 2015
copyright: Some rights reserved
