# =============================================
# SITE CONFIG
# =============================================

name: Tawja
homepage: http://www.tawja.org
lang: en
slogan: Base Template
year: 2015
copyright: Some rights reserved
